# SPDX-FileCopyrightText: 2023 Christina Sørensen
# SPDX-FileContributor: Christina Sørensen
#
# SPDX-License-Identifier: AGPL-3.0-only

[package]
name = "nix-weather"
description = "Guix weather, for nix!"
authors = ["Christina Sørensen <christina@cafkafk.com>"]
categories = ["command-line-utilities"]
edition = "2021"
rust-version = "1.74.0"
readme = "README.md"
license = "AGPL-3.0-only"
version = "0.0.1"
build = "build.rs"

[dependencies]
async-recursion = "1.0.5"
clap = { version = "4.5.1", features = ["cargo"] }
dns-lookup = "2.0.4"
domain = { version = "0.9.3", features = ["tokio", "resolv"] }
futures = "0.3.30"
gethostname = "0.4.3"
itertools = "0.12.1"
log = "0.4.21"
openssl = { version = "0.10.63" }
pretty_env_logger = "0.5.0"
rayon = "1.10.0"
reqwest = { version = "0.11.24", features = ["blocking"] }
scraper = "0.18.1"
serde = "1.0.197"
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["macros", "full"] }

[build-dependencies]
clap = { version = "4.5.1", features = ["cargo"] }
clap_complete = "4"
clap_mangen = "0.2.20"
gethostname = "0.4.3"
