# SPDX-FileCopyrightText: 2024 Christina Sørensen
#
# SPDX-License-Identifier: EUPL-1.2

name: Security audit
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - '.github/workflows/audit.yml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - 'deny.toml'
  pull_request:
    branches: [main]
jobs:
  security_audit:
    runs-on: native
    steps:
      - uses: actions/checkout@v4
      - name: Scan for vulnerabilities
        run: nix develop --accept-flake-config --command cargo deny check
