# SPDX-FileCopyrightText: 2024 Christina Sørensen
#
# SPDX-License-Identifier: EUPL-1.2

name: Security audit
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - '.github/workflows/audit.yml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - 'deny.toml'
jobs:
  security_audit:
    runs-on: native
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/taiki-e/install-action@cargo-deny
      - name: Scan for vulnerabilities
        run: cargo deny check
