# SPDX-FileCopyrightText: 2024 Christina Sørensen
#
# SPDX-License-Identifier: EUPL-1.2

name: conventional commits
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true
jobs:
  check:
    name: conventional commits
    runs-on: native
    steps:
      - uses: actions/checkout@v4
      - uses: actions/action-conventional-commits@v1.3.0
